backend:
  name: git-gateway
  branch: main
local_backend: true

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages Fixes"
    files:
      - file: "content/_index.md"
        label: "Accueil (Hub)"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "content/dj/_index.md"
        label: "Page DJ"
        name: "dj"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "content/contact/_index.md"
        label: "Page Contact"
        name: "contact"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

  - name: "projets"
    label: "Projets & Facettes"
    folder: "content/projets"
    filter: { field: "projetType", value: "project" }
    create: true
    slug: "{{slug}}"
    path: "{{slug}}/index"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Date", name: "date", widget: "date" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Projet Type", name: "projetType", widget: "hidden", default: "project" }
